name: Build and Test
 
on:
  pull_request:
    branches:
      - main

jobs:
  yarn-base-test:

    strategy:
      matrix:
        # node-version: [14.x, 16.x]
        node-version: [14.x]
        targets:
          - path: dockerode-example
            test: false
            lint: true
          - path: hello-electron
            test: false
            lint: true
          - path: next-examples/cognito-aws-console-example/app
            test: true
            lint: true
          - path: next-examples/cognito-aws-console-example/infra
            test: true
            lint: false
          - path: next-examples/cognito-s3-example
            test: true
            lint: true
          - path: next-examples/cognito-s3-example/infra
            test: true
            lint: false
          - path: next-examples/next-auth0-example
            test: true
            lint: true
          - path: next-examples/mdx-example
            test: true
            lint: true
          - path: next-examples/next-ts-examples
            test: true
            lint: true
          - path: next-examples/vnc-example
            test: true
            lint: true
          - path: elm-electron
            test: true
            lint: false

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build and lint
        env:
          NEXT_PUBLIC_AUTH0_DOMAIN: test
          NEXT_PUBLIC_AUTH0_CLIENT_ID: test
          NEXT_PUBLIC_CALLBACK_URL: http://localhost:3000
        run: |
          cd ${{ matrix.targets.path }}
          yarn install
          if [ ${{ matrix.targets.lint }} == "true" ]; then
            yarn lint --fix
          fi
          yarn build
          if [ ${{ matrix.targets.path }} == "true" ]; then
            yarn test
          fi

      - name: Pull request auto merge enabler
        if: github.event_name == 'pull_request'
        uses: poad/github-pull-request-auto-merge-enable-action@v1.0.0
        with:
          pull_request_id: ${{ github.event.pull_request.node_id }}
          github_token: ${{ secrets.PERSONAL_TOKEN_FOR_GITHUB_ACTIONS }}
          repository: ${{ github.event.repository.name }}
          owner: ${{ github.repository_owner }}
          merge_method: SQUASH
