name: Build and Test
 
on:
  pull_request:
    branches:
      - main

jobs:
  yarn-base-test:

    strategy:
      matrix:
        targets:
          - path: dockerode-example
            test: false
            lint: true
          - path: hello-electron
            test: false
            lint: true
          - path: next-examples/cognito-aws-console-example/app
            test: true
            lint: true
          - path: next-examples/cognito-aws-console-example/infra
            test: true
            lint: false
          - path: next-examples/cognito-s3-example
            test: true
            lint: true
          - path: next-examples/cognito-s3-example/infra
            test: true
            lint: false
          - path: next-examples/next-auth0-example
            test: true
            lint: true
          - path: next-examples/next-ts-examples
            test: true
            lint: true
          # - path: nuxt-example/hello-world
          #   test: true
          #   lint: false
          # - path: nuxt-example/nuxt-ts-spa-example
          #   test: true
          #   lint: false
          # - path: nuxt-example/nuxt-typescript-example
          #   test: true
          #   lint: false
          # - path: nuxt-example/nuxt-vuetify-example
          #   test: true
          #   lint: false
          - path: elm-electron
            test: true
            lint: false

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Build and lint
        env:
          AUTH0_DOMAIN: test
          AUTH0_CLIENT_ID: test
          CALLBACK_URL: http://localhost:3000
        run: |
          cd ${{ matrix.targets.path }}
          yarn install
          if [ ${{ matrix.targets.lint }} == "true" ]; then
            yarn lint --fix
          fi
          yarn build
          if [ ${{ matrix.targets.path }} == "true" ]; then
            yarn test
          fi
